server:
  port: 5004

spring:
  application:
    name: orderService

  data:
    mongodb:
      uri: mongodb://localhost:27017/orderDb
      repositories:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/