server:
  port: 5001

spring:
  profiles:
    active:
      - local
  application:
    name: RESTAURANT-LISTING
  # This name is responsible for service registering on eureka server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect  # Dialect is an interface used to convert ORM-based language into database-specific language
        # Example: findAll() translates to `SELECT * FROM dbName;`