server:
  port: 5001

spring:
  application:
    name: restaurantListing  # This name is responsible for service registering on eureka server.

  datasource:
    url: jdbc:mysql://localhost:3306/restaurantServiceDb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Dialect is an interface used to convert ORM-based language into database-specific language
        # Example: findAll() translates to `SELECT * FROM dbName;`

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/